local lspsaga = require("lspsaga")

lspsaga.setup({
  ui = {
    winbar_prefix = '',
    border = "solid",
    devicon = true,
    foldericon = true,
    title = true,
    expand = "⊞",
    collapse = "⊟",
    code_action = " ", -- "💡",
    lines = { '┗', '┣', '┃', '━', '┏' },
    kind = {},
    button = { '', '' },
    imp_sign = '󰳛 ',
    use_nerd = true,
  },
  hover = {
    max_width = 0.9,
    max_height = 0.8,
    open_link = 'gx',
    open_cmd = '!chrome',
  },
  diagnostic = {
    show_code_action = true,
    -- show_source = true,
    show_layout = "float",
    show_normal_height = 10,
    jump_num_shortcut = true,
    max_width = 0.8,
    max_height = 0.6,
    max_show_width = 0.9,
    max_show_height = 0.6,
    text_hl_follow = true,
    border_follow = true,
    extend_relatedInformation = false,
    diagnostic_only_current = false,
    keys = {
      exec_action = "o",
      quit = "q",
      toggle_or_jump = "<CR>",
      quit_in_show = { "q", "<ESC>" },
    },
  },
  code_action = {
    num_shortcut = true,
    show_server_name = true,
    extend_gitsigns = true,
    keys = {
      quit = "<C-c>",
      exec = "<CR>",
    },
  },
  lightbulb = {
    enable = false,
    sign = true,
    debounce = 10,
    sign_priority = 40,
    virtual_text = true,
    enable_in_insert = true,
  },
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
  preview = {
    lines_above = 10,
    lines_below = 50,
  },
  request_timeout = 2000,
  finder = {
    methods = {},
    default = "ref+imp",
    layout = "float",
    silent = false,
    filter = {},
    keys = {
      -- edit = "<CR>",
      shuttle = "[w",
      toggle_or_open = "o",
      vsplit = "s",
      split = "i",
      tabe = "t",
      tabnew = "r",
      quit = "q",
      close = "<C-c>k",
    },
  },
  definition = {
    keys = {
      edit = "<C-c>o",
      vsplit = "<C-c>v",
      split = "<C-c>i",
      tabe = "<C-c>t",
      quit = "q",
      close = "<Esc>",
    },
  },
  rename = {
    in_select = false,
    auto_save = false,
    keys = {
      quit = "<C-c>",
      exec = "<CR>",
      select = "x",
    },
  },
  symbol_in_winbar = {
    enable = true,
    separator = " ",
    hide_keyword = false,
    show_file = true,
    folder_level = 1,
    -- respect_root = false,
    color_mode = true,
    dely = 300,
  },
  outline = {
    win_position = "right",
    win_width = 30,
    auto_preview = true,
    detail = true,
    auto_close = true,
    close_after_jump = false,
    layout = "normal",
    max_height = 0.5,
    left_width = 0.3,
    keys = {
      toggle_or_jump = "o",
      quit = "q",
      jump = "e",
    },
  },
  callhierarchy = {
    layout = "float",
    keys = {
      edit = "e",
      vsplit = "s",
      split = "i",
      tabe = "t",
      close = "<C-c>k",
      quit = "q",
      shuttle = "[w",
      toggle_or_req = "u",
    },
  },
  implement = {
    enable = true,
    sign = false,
    lang = {},
    virtual_text = true,
    priority = 100,
  },
  beacon = {
    enable = true,
    frequency = 7,
  },
})
