setlocal autoindent
setlocal cindent
setlocal cinwords=if,elif,else,for,while,try,except,finally,def,class,with
setlocal colorcolumn=100
setlocal copyindent
setlocal expandtab
setlocal formatoptions=jntcoql
setlocal nosmartindent
setlocal shiftwidth=4
setlocal smarttab
setlocal softtabstop=4
setlocal tabstop=8
