setlocal autoindent
setlocal cindent
setlocal cinwords=if,elif,else,for,while,try,except,finally,def,class,with
setlocal colorcolumn=99
setlocal copyindent
setlocal expandtab
setlocal expandtab
setlocal formatoptions+=croq
setlocal shiftwidth=4
setlocal nosmartindent
setlocal smarttab
setlocal softtabstop=4
setlocal tabstop=8
